---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1-13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - NODE_TESTS=true

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install: ./scripts/before-install.sh
install: ./scripts/install.sh
script: ./scripts/run-tests.sh
